-- MySQL Script generated by MySQL Workbench
-- Tue May 28 15:34:07 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trema
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `trema_jsp` DEFAULT CHARACTER SET utf8 ;
USE `trema_jsp` ;

-- -----------------------------------------------------
-- Table `trema_jsp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trema_jsp`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `usertype` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trema_jsp`.`HumanResource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trema_jsp`.`humanresource` (
  `idHR` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `iduser` INT NOT NULL,
  PRIMARY KEY (`idHR`),
  INDEX `fk_HumanResource_User1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_HumanResource_User1`
    FOREIGN KEY (`iduser`)
    REFERENCES `trema_jsp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trema_jsp`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trema_jsp`.`material` (
  `idmaterial` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `quantita` VARCHAR(45) NULL,
  `idHR` INT NOT NULL,
  PRIMARY KEY (`idmaterial`),
  INDEX `fk_Material_HumanResource1_idx` (`idHR` ASC) VISIBLE,
  CONSTRAINT `fk_Material_HumanResource1`
    FOREIGN KEY (`idHR`)
    REFERENCES `trema_jsp`.`humanresource` (`idHR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trema_jsp`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trema_jsp`.`project` (
  `idproject` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `descrizione` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `iduser` INT NOT NULL,
  PRIMARY KEY (`idproject`),
  INDEX `fk_Project_User1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_Project_User1`
    FOREIGN KEY (`iduser`)
    REFERENCES `trema_jsp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trema_jsp`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trema_jsp`.`task` (
  `idtask` INT NOT NULL AUTO_INCREMENT,
  `descrizione_task` VARCHAR(45) NULL,
  `idHR` INT NOT NULL,
  `idproject` INT NOT NULL,
  PRIMARY KEY (`idtask`),
  INDEX `fk_Task_HumanResource1_idx` (`idHR` ASC) VISIBLE,
  INDEX `fk_Task_Project1_idx` (`idproject` ASC) VISIBLE,
  CONSTRAINT `fk_Task_HumanResource1`
    FOREIGN KEY (`idHR`)
    REFERENCES `trema_jsp`.`humanresource` (`idHR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Project1`
    FOREIGN KEY (`idproject`)
    REFERENCES `trema_jsp`.`project` (`idproject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO user (username,password,usertype)
values ('admin','admin','admin'),('user','user','project_manager'),('user3','user3','project_manager'),('user4','user4','HR_manager'),('user5','user5','HR_manager'),('admin1','admin1','admin');

INSERT INTO humanresource (name,surname,iduser)
values ('Gianluca','Di Nanna',1),('Ali','Tavakkoli',2),('Adrian','Papuc',2),('Angel','Mata',2),('Dino','Zoff',3),('Carlo','Cracco',1);

INSERT INTO material (tipo,quantita,idHR)
values ('Computer',5,3),('Martello',23,2),('Calce',3,2),('Macchina da cucire',5,4),('Hard Disk',43,3),('Cazzola',7,6);

INSERT INTO project (name,descrizione,tipo,iduser)
values ('Trema','Progetto Informatico','Informatica',1),('Dorse','Progetto Edilizio','Edile',3),('Triplan','Progetto Informatico','Informatica',2),('SportUp','Progetto Tessile','Tessuti',6),('Incoro','Progetto Edilizio','Edile',3),('Worse','Progetto Informatico','Informatica',6);

INSERT INTO task (descrizione_task,idHR,idproject)
values ('Progettazione',2,1),('Progettazione',1,2),('Consegna',3,3),('Sviluppo',4,4),('Progettazione',5,5),('Sviluppo',6,6);
