-- MySQL Script generated by MySQL Workbench
-- Wed May 22 15:35:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trema
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `trema` DEFAULT CHARACTER SET utf8 ;
USE `trema` ;

-- -----------------------------------------------------
-- Table `trema`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trema`.`User` (
  `idUser` INT NOT NULL,
  `Username` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trema`.`HumanResource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trema`.`HumanResource` (
  `idHR` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Phone` VARCHAR(15) NULL,
  `Speciality` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idHR`),
  INDEX `fk_HumanResource_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_HumanResource_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `trema`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trema`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trema`.`Material` (
  `idMaterial` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Model` VARCHAR(45) NULL,
  `Category` VARCHAR(45) NULL,
  `Inventory` VARCHAR(45) NULL,
  PRIMARY KEY (`idMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trema`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trema`.`Project` (
  `idProject` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Category` VARCHAR(45) NULL,
  `StartDate` DATE NULL,
  PRIMARY KEY (`idProject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trema`.`TaskDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trema`.`TaskDetails` (
  `idTaskDetails` INT NOT NULL,
  `HumanResource_idHR` INT NOT NULL,
  `Material_idMaterial` INT NOT NULL,
  `Project_idProject` INT NOT NULL,
  PRIMARY KEY (`idTaskDetails`),
  INDEX `fk_TaskDetails_HumanResource1_idx` (`HumanResource_idHR` ASC) VISIBLE,
  INDEX `fk_TaskDetails_Material1_idx` (`Material_idMaterial` ASC) VISIBLE,
  INDEX `fk_TaskDetails_Project1_idx` (`Project_idProject` ASC) VISIBLE,
  CONSTRAINT `fk_TaskDetails_HumanResource1`
    FOREIGN KEY (`HumanResource_idHR`)
    REFERENCES `trema`.`HumanResource` (`idHR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TaskDetails_Material1`
    FOREIGN KEY (`Material_idMaterial`)
    REFERENCES `trema`.`Material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TaskDetails_Project1`
    FOREIGN KEY (`Project_idProject`)
    REFERENCES `trema`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
